### ISSUE TITLE
check - statistics file isn't created

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#61]

**Comment by hagai-lvi** [comment]
- The scenario that caused this: local with terminate=false, with 1000 tweets, then local with 5 tweets with terminate=true
- I've checked and saw that the statistics file was uploaded to s3 by the manager

```
com.bgu.dsp.main.Execute /Users/hagai_lvi/javaProjects/distributedSystems/tweets.txt out_small_terminate.html 1 terminate
LOCAL 2016-05-10 11:17:17 INFO  S3Utils:46 - Using production S3 with local credentials
LOCAL 2016-05-10 11:17:26 INFO  LocalMachine:95 - upload successful: /Users/hagai_lvi/javaProjects/distributedSystems/tweets.txt
LOCAL 2016-05-10 11:17:26 INFO  SQSUtils:107 - Using production SQS with local credentials
LOCAL 2016-05-10 11:17:30 INFO  LocalMachine:69 - message sent to server: {"sqsName":"28097f04-beb4-4bc8-a3cb-5c1cb1e07e3e","bucketName":"local-to-manager-bucket","key":"inputFile","terminate":false,"taskID":"22f238bb-6e2f-4b04-ac0d-de3bc0ac67d1","tasksPerWorker":1.0}
LOCAL 2016-05-10 11:17:33 INFO  LocalMachine:35 - Using an already active manager
LOCAL 2016-05-10 11:17:33 INFO  LocalMachine:146 - heartbit started.
LOCAL 2016-05-10 11:17:33 INFO  SqsLooper:48 - starting sqs looper
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:144 - Writing one tweet to file.
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:144 - Writing one tweet to file.
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:144 - Writing one tweet to file.
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:144 - Writing one tweet to file.
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:144 - Writing one tweet to file.
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:144 - Writing one tweet to file.
LOCAL 2016-05-10 11:17:38 DEBUG TweetsToHtmlConverter:101 - Output file writing took 12 milliseconds.
LOCAL 2016-05-10 11:18:00 ERROR SqsLooper:114 - Timed out when waiting for statistics file from manager
LOCAL 2016-05-10 11:18:00 INFO  SqsLooper:68 - download statistics file failed.
LOCAL 2016-05-10 11:18:00 INFO  SqsLooper:28 - deleting queue and shutting down .
LOCAL 2016-05-10 11:18:01 INFO  LocalMachine:165 - heartbit interrupted
java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep(Native Method)
    at com.bgu.dsp.main.LocalMachine$HeartBit.run(LocalMachine.java:161)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Process finished with exit code 0
```
