### ISSUE TITLE
File not found exception in the manager

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#70]
The scenario:

``` sh
set -o verbose

java -jar dsp1-1.0-SNAPSHOT-jar-with-dependencies.jar tweets.txt first.html 1 &


sleep 120

for i in {1..10}
do
   java -jar dsp1-1.0-SNAPSHOT-jar-with-dependencies.jar tweets.txt tweets$i.html 1 &
done

sleep 30


java -jar dsp1-1.0-SNAPSHOT-jar-with-dependencies.jar tweets.txt last.html 1 terminate
```

The exception:

```
java.io.FileNotFoundException: aws-local-to-manager-bucket-inputFile (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at com.bgu.dsp.common.protocol.localtomanager.NewTaskCommand.postTweetsToQueue(NewTaskCommand.java:236)
    at com.bgu.dsp.common.protocol.localtomanager.NewTaskCommand.run(NewTaskCommand.java:106)
    at com.bgu.dsp.manager.Main.lambda$main$0(Main.java:109)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by hagai-lvi** [comment]
might be related to #68
